service: mapproxy
provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-west-1
  memorySize: 256
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::mapproxy-lambda-demo*"
  environment:
    MAPPROXY_LIB_PATH: /var/task/lib:/var/task/mapproxy

plugins:
  - serverless-wsgi
  - serverless-apigw-binary

custom:
  wsgi:
    app: config.app
  apigwBinary:
    types:
      - '*/*'

functions:
  app:
    handler: wsgi_handler.handler
    layers:
      - arn:aws:lambda:us-west-1:081097954549:layer:proj:9
    events:
      - http:
          path: /{proxy+}
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: /
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false